# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.9.0
      - run: cargo build
      - run: cargo install wasm-pack
      - run: wasm-pack build --target web --release --mode no-install --scope console1024
      - uses: actions/setup-node@v4
        with:
          node-version: 20

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: cd pkg
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
